export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export enum UserActionTypes {
    USER_AUTHORIZE='USER_AUTHORIZE',
    USER_LOGOUT='USER_LOGOUT'
}

export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCSESS = 'REGISTER_SUCCSESS';
export const REGISTER_RESET = 'REGISTER_RESET';

export const APP_LOADED = 'APP_LOADED';

export enum CategoryActionTypes {
     CATEGORY_ADD = 'CATEGORY_ADD',
     CATEGORY_DELETE = 'CATEGORY_DELETE',
     CATEGORY_GET = 'CATEGORY_GET',
     SHOW_ADD_MODAL = 'SHOW_ADD_MODAL',
     HIDE_ADD_MODAL = 'HIDE_ADD_MODAL',
}
